import {configureLocalization} from '@lit/localize';
import {sourceLocale, targetLocales} from './locales/locale-codes.js';

// For runtime mode, we need to load locale modules dynamically
// The actual locale modules will be generated by lit-localize build
export const {getLocale, setLocale} = configureLocalization({
  sourceLocale,
  targetLocales,
  loadLocale: async (locale: string) => {
    // In runtime mode, locales are loaded from generated files
    // For now, we'll use a simple fallback
    try {
      return await import(`./locales/${locale}.js`);
    } catch {
      return await import(`./locales/${sourceLocale}.js`);
    }
  },
});

// Get initial locale from URL or settings
export function getInitialLocale(): string {
  const query = new URLSearchParams(window.location.search);
  const lang = query.get('lang');
  if (lang) {
    return lang.substring(0, 2).toLowerCase();
  }
  return sourceLocale;
}

// Initialize locale on load
export async function initializeLocale(): Promise<void> {
  const locale = getInitialLocale();
  await setLocale(locale);
}

