import {configureLocalization, LocaleModule} from '@lit/localize';
import {sourceLocale, targetLocales} from './locales/locale-codes';

import * as pl from './locales/pl';

// For runtime mode, we need to load locale modules dynamically
// The actual locale modules will be generated by lit-localize build
export const {getLocale, setLocale} = configureLocalization({
  sourceLocale,
  targetLocales,
  loadLocale: async (locale: string): Promise<LocaleModule> => {
    switch (locale) {
      case 'pl':
        return pl;
      case 'en':
        return { templates: {} };
      default:
        console.warn(`Unknown locale ${locale}, using source locale ${sourceLocale}`);
        return { templates: {} };
    }
  },
});

export function getInitialLocale(): string {
  return document.documentElement.lang || new URLSearchParams(window.location.search).get('lang') || sourceLocale;
}

// Initialize locale on load
export async function initializeLocale(): Promise<void> {
  const locale = getInitialLocale();
  if (locale === sourceLocale || targetLocales.includes(locale as any)) {
    await setLocale(locale);
  } else {
    await setLocale(sourceLocale);
  }
}

